### ISSUE TITLE
Documentation on training and inferencing

### ISSUE THREAD

**Issue by seekingdeep** [lanwuwei/GigaBERT#1]
Documentation on training, finetuning, inferencing the model
how can gigabert be used for neural machine translation

**Comment by lanwuwei** [comment]
GigaBERT has the same usage as BERT, you can check some papers, for example:
[Incorporating BERT into Neural Machine Translation](https://arxiv.org/abs/2002.06823)
[On the use of BERT for Neural Machine Translation](https://www.aclweb.org/anthology/D19-5611.pdf)
