### ISSUE TITLE
License of the released models

### ISSUE THREAD

**Issue by Paethon** [lanwuwei/GigaBERT#2]
Hi

Could you tell me which license the trained models are released under (BERT uses Apache 2.0)? Without knowing this, it is pretty difficult to use them for anything.

Cheers, Sebastian

**Comment by lanwuwei** [comment]
Hi Sebastian,

Sorry for the late reply. After syncing with other co-authors, we decided to use the same license as BERT, Apache 2.0.

Best,
Wuwei

**Comment by Paethon** [comment]
Thanks!
